//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcFactorWebServicesTwo.WSTec {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSTec.WTecnicoSoap")]
    public interface WTecnicoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insertar(string email, string pass, string rut, string nombre, string apellido, int telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertarAsync(string email, string pass, string rut, string nombre, string apellido, int telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buscar(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WTecnicoSoapChannel : PcFuctorWebServicesTwo.WSTec.WTecnicoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WTecnicoSoapClient : System.ServiceModel.ClientBase<PcFuctorWebServicesTwo.WSTec.WTecnicoSoap>, PcFuctorWebServicesTwo.WSTec.WTecnicoSoap {
        
        public WTecnicoSoapClient() {
        }
        
        public WTecnicoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WTecnicoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WTecnicoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WTecnicoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string Insertar(string email, string pass, string rut, string nombre, string apellido, int telefono) {
            return base.Channel.Insertar(email, pass, rut, nombre, apellido, telefono);
        }
        
        public System.Threading.Tasks.Task<string> InsertarAsync(string email, string pass, string rut, string nombre, string apellido, int telefono) {
            return base.Channel.InsertarAsync(email, pass, rut, nombre, apellido, telefono);
        }
        
        public System.Data.DataSet Buscar(string email) {
            return base.Channel.Buscar(email);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string email) {
            return base.Channel.BuscarAsync(email);
        }
    }
}
