//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.WSUsuarios {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSUsuarios.ValidarUsuariosSoap")]
    public interface ValidarUsuariosSoap {
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarUsuario", ReplyAction="*")]
        GUI.WSUsuarios.ValidarUsuarioResponse ValidarUsuario(GUI.WSUsuarios.ValidarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<GUI.WSUsuarios.ValidarUsuarioResponse> ValidarUsuarioAsync(GUI.WSUsuarios.ValidarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        GUI.WSUsuarios.EliminarResponse Eliminar(GUI.WSUsuarios.EliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<GUI.WSUsuarios.EliminarResponse> EliminarAsync(GUI.WSUsuarios.EliminarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public GUI.WSUsuarios.ValidarUsuarioRequestBody Body;
        
        public ValidarUsuarioRequest() {
        }
        
        public ValidarUsuarioRequest(GUI.WSUsuarios.ValidarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public ValidarUsuarioRequestBody() {
        }
        
        public ValidarUsuarioRequestBody(string email, string pass) {
            this.email = email;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUI.WSUsuarios.ValidarUsuarioResponseBody Body;
        
        public ValidarUsuarioResponse() {
        }
        
        public ValidarUsuarioResponse(GUI.WSUsuarios.ValidarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ValidarUsuarioResult;
        
        public ValidarUsuarioResponseBody() {
        }
        
        public ValidarUsuarioResponseBody(int ValidarUsuarioResult) {
            this.ValidarUsuarioResult = ValidarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Eliminar", Namespace="http://tempuri.org/", Order=0)]
        public GUI.WSUsuarios.EliminarRequestBody Body;
        
        public EliminarRequest() {
        }
        
        public EliminarRequest(GUI.WSUsuarios.EliminarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public EliminarRequestBody() {
        }
        
        public EliminarRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUI.WSUsuarios.EliminarResponseBody Body;
        
        public EliminarResponse() {
        }
        
        public EliminarResponse(GUI.WSUsuarios.EliminarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int EliminarResult;
        
        public EliminarResponseBody() {
        }
        
        public EliminarResponseBody(int EliminarResult) {
            this.EliminarResult = EliminarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidarUsuariosSoapChannel : GUI.WSUsuarios.ValidarUsuariosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidarUsuariosSoapClient : System.ServiceModel.ClientBase<GUI.WSUsuarios.ValidarUsuariosSoap>, GUI.WSUsuarios.ValidarUsuariosSoap {
        
        public ValidarUsuariosSoapClient() {
        }
        
        public ValidarUsuariosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidarUsuariosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidarUsuariosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidarUsuariosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI.WSUsuarios.ValidarUsuarioResponse GUI.WSUsuarios.ValidarUsuariosSoap.ValidarUsuario(GUI.WSUsuarios.ValidarUsuarioRequest request) {
            return base.Channel.ValidarUsuario(request);
        }
        
        public int ValidarUsuario(string email, string pass) {
            GUI.WSUsuarios.ValidarUsuarioRequest inValue = new GUI.WSUsuarios.ValidarUsuarioRequest();
            inValue.Body = new GUI.WSUsuarios.ValidarUsuarioRequestBody();
            inValue.Body.email = email;
            inValue.Body.pass = pass;
            GUI.WSUsuarios.ValidarUsuarioResponse retVal = ((GUI.WSUsuarios.ValidarUsuariosSoap)(this)).ValidarUsuario(inValue);
            return retVal.Body.ValidarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI.WSUsuarios.ValidarUsuarioResponse> GUI.WSUsuarios.ValidarUsuariosSoap.ValidarUsuarioAsync(GUI.WSUsuarios.ValidarUsuarioRequest request) {
            return base.Channel.ValidarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI.WSUsuarios.ValidarUsuarioResponse> ValidarUsuarioAsync(string email, string pass) {
            GUI.WSUsuarios.ValidarUsuarioRequest inValue = new GUI.WSUsuarios.ValidarUsuarioRequest();
            inValue.Body = new GUI.WSUsuarios.ValidarUsuarioRequestBody();
            inValue.Body.email = email;
            inValue.Body.pass = pass;
            return ((GUI.WSUsuarios.ValidarUsuariosSoap)(this)).ValidarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUI.WSUsuarios.EliminarResponse GUI.WSUsuarios.ValidarUsuariosSoap.Eliminar(GUI.WSUsuarios.EliminarRequest request) {
            return base.Channel.Eliminar(request);
        }
        
        public int Eliminar(string email) {
            GUI.WSUsuarios.EliminarRequest inValue = new GUI.WSUsuarios.EliminarRequest();
            inValue.Body = new GUI.WSUsuarios.EliminarRequestBody();
            inValue.Body.email = email;
            GUI.WSUsuarios.EliminarResponse retVal = ((GUI.WSUsuarios.ValidarUsuariosSoap)(this)).Eliminar(inValue);
            return retVal.Body.EliminarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUI.WSUsuarios.EliminarResponse> GUI.WSUsuarios.ValidarUsuariosSoap.EliminarAsync(GUI.WSUsuarios.EliminarRequest request) {
            return base.Channel.EliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUI.WSUsuarios.EliminarResponse> EliminarAsync(string email) {
            GUI.WSUsuarios.EliminarRequest inValue = new GUI.WSUsuarios.EliminarRequest();
            inValue.Body = new GUI.WSUsuarios.EliminarRequestBody();
            inValue.Body.email = email;
            return ((GUI.WSUsuarios.ValidarUsuariosSoap)(this)).EliminarAsync(inValue);
        }
    }
}
